#!/bin/sh
# /etc/init.d/bikemon

### BEGIN INIT INFO
# Provides:          bikemon
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop bicycle monitoring program
### END INIT INFO

case "$1" in
    start)
        echo "Starting Bicycle Monitor"
		cd /home/pi/Bicycle-Monitor/
        python3 main.py > log.txt &
        ;;
    stop)
        echo "Stopping Bicycle Monitor"
        killall python3
        ;;
    *)
        echo "Usage: /etc/init.d/bikemon start|stop"
        exit 1
        ;;
esac

exit 0